#!/bin/bash

askshell_version=2

##
 # Ask a questions.
 #
 # @param "$1"
 #   The title's question
 # @param $2
 #   The variable to be filled
askshell_ask() {
    read -p "$1" $2
}

##
 # Forbids the answer to be null
 #
 # @param "$1"
 #   The title's question
 # @param $2
 #   The variable to be filled
askshell_notempty() {

    askshell_ask "$1" $2 
    answer=${!2}

    if [ ${#answer} -eq 0 ]; then
        echo You did not provides any answer to "$1" question. Please, provides something.
        askshell_notempty "$1" $2
    fi
}

##
 # Checks if the argument is a file
 #
 # @param "$1"
 #   The title's question
 # @param $2
 #   The path for the file
askshell_file() {

    askshell_notempty "$1" "$2"
    answer=${!2}

    if [ ! -f "$answer" ]; then
        echo The answer provided is not a file.
        askshell_file "$1" "$2"
    fi
}